#ifndef CONTROL_PIN_ALLOCATIONS_H
#define CONTROL_PIN_ALLOCATIONS_H

#include <Arduino.h>

#define PIN_DEBUG_RX PA10
#define PIN_DEBUG_TX PA9

#define PIN_MAIN_SDA PB7
#define PIN_MAIN_SCL PB6

#define PIN_CONTROLLER_SDA PB11
#define PIN_CONTROLLER_SCL PB10

#define PIN_BUZZER PB1

#define PIN_LED_STATUS_1 PA8
#define PIN_LED_STATUS_2 PA4

#define NUM_SERVOS 5
#define PIN_SERVO_1 PB12
#define PIN_SERVO_2 PB13
#define PIN_SERVO_3 PB14
#define PIN_SERVO_4 PB15
#define PIN_SERVO_5 PB9

#define NUM_POTENTIOMETERS 4
#define PIN_POTENTIOMETER_1 PA3
#define PIN_POTENTIOMETER_2 PA2
#define PIN_POTENTIOMETER_3 PA1
#define PIN_POTENTIOMETER_4 PA0

#define NUM_LED_FIELDS 4
#define PIN_LED_FIELD_1 PA5
#define PIN_LED_FIELD_2 PA6
#define PIN_LED_FIELD_3 PA7
#define PIN_LED_FIELD_4 PB0
#define PIN_LED_FIELD_ACTIVE HIGH

extern const int PIN_SERVOS[NUM_SERVOS];
extern const int PIN_POTENTIOMETERS[NUM_POTENTIOMETERS];
extern const int PIN_LED_FIELD[NUM_LED_FIELDS];

#endif